alias ll='ls -la'
alias sss='eval `ssh-agent` && ssh-add'
alias gfp='git fetch --prune && git pull'
alias gct='git checkout test'
alias gcm='git checkout main || git checkout master'
alias gbv='git branch -vv'
alias glo='git log --oneline'
alias glg='git log --graph --pretty=oneline --abbrev-commit --branches'
alias p='pnpm'
alias puli='pnpm update --latest --interactive'
alias pci='rm -rf node_modules/ && rm -rf pnpm-lock.yaml && rm -rf $(pnpm store path) && p update --latest --ignore-scripts && pnpm audit'
alias diffi='diff --side-by-side --suppress-common-lines --color=always'
