# Makefile template
# Usage: copy to project root and adapt targets

.PHONY: help build run clean

help: ## show this help
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | awk 'BEGIN {FS = ":.*?## "}; {printf "  \033[36m%-15s\033[0m %s\n", $$1, $$2}'

build: ## build the project
	@echo "TODO: add build commands"

run: ## run the project
	@echo "TODO: add run commands"

clean: ## remove build artifacts
	@echo "TODO: add clean commands"
